apiVersion: shipa.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: argo-demo1
spec:
  forProvider:
    name: argo-demo1
    endpoint:
      addresses: ["https://xx.xx.xx.xx"]
      caCert: |
         -----BEGIN CERTIFICATE-----
         -----END CERTIFICATE-----
      token: xxxxxxxxxxxxxxxxxxxxxxxx
    resources:
      frameworks:
        name: ["cp-dev", "cp-qa"]

---

apiVersion: shipa.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: argo-demo2
spec:
  forProvider:
    name: argo-demo2
    endpoint:
      addresses: ["https://xx.xx.xx.xx"]
      caCert: |
         -----BEGIN CERTIFICATE-----
         -----END CERTIFICATE-----
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    resources:
      frameworks:
        name: ["cp-prod"]
